# spring configuration
spring:
  application:
    name: ex01

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.64.5:3306/bookmall?charset=utf8
    username: bookmall
    password: bookmall
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: public
        hbm2ddl:
          auto: validate

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
