# spring configuration
spring:
  application:
    name: ex02

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.64.5:3306/jpadb?charset=utf8
    username: jpadb
    password: jpadb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    defer-datasource-initialization: false # 뒤로 연기하지말고 먼저하라는 의미, true는 em쪽 설정이 다 되고 나서 datasource초기화 한다는 의미라서 설정이 긴 경우가 있기에 잘 안씀.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: public
        hbm2ddl:
          auto: create

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
