# spring configuration
spring:
  application:
    name: ex02
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.64.5:3306/jpadb?charset=utf8
    username: jpadb
    password: jpadb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      # test를 위해 name mapping strategy 수정: Entity Definition Naming(Standard)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 엔터티이름을 그대로 사용하게끔 함.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
