# spring configuration
spring:
  application:
    name: ex02

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.64.5:3306/webdb?charset=utf8
    username: webdb
    password: webdb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: public
        hbm2ddl:
          auto: validate # 우리가 만들었던 물리DB를 매핑할때 validate 이용

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
