# spring configuration
spring:
   application:
      name: mysite
   
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
   
   # aop
   aop:
      auto: true
      proxy-target-class: true
      
   # thymeleaf
   thymeleaf:
      check-template-location: true
      mode: HTML
      prefix: classpath:templates/
      suffix: .html
      encoding: UTF-8
      cache: false
      
   # mvc
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
      # view:
      #   prefix: /WEB-INF/views/
      #   suffix: .jsp
       
   # web  
   web:
      resources:
         static-locations: file:/Users/sohyunahn/ash/poscodx2024/mysite-uploads/, classpath:assets/
      
   # message resources(internationalization, i18n)
   messages:
      basename: messages/message
      encoding: utf-8
      always-use-message-format: true
      
   # multipart-resolver 
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 10MB
      
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.64.5:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
      

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
      
         
# server configuration
server:
   port: 8088
   servlet:
      context-path: /mysite7
      encoding:
         charset: utf-8
         enabled: true
   error:
      whitelabel:
         enabled: false
      path: /error
      
         
# logging
logging:
   config: classpath:logback.xml